version: "3"
services:
  redis:
    image: redis:7.0
    network_mode: bridge

  db:
    image: postgres:16.4
    network_mode: bridge
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --auth-host=md5

  jabber:
    build: .
    network_mode: bridge
    extra_hosts:
      - jabber.local:127.0.0.1
    volumes:
      - ./:/app
      - ./:/opt/modules.d/sources/mod_mam2sidekiq
      - ./config/ejabberd.yml:/etc/ejabberd/ejabberd.yml
      - ./config/ejabberdctl.cfg:/etc/ejabberd/ejabberdctl.cfg
    links:
      - redis
      - db
    environment:
      MDNS_HOSTNAME: jabber.local

  e2e:
    image: ruby:2.7
    network_mode: bridge
    volumes:
      - ./tests/e2e:/app
    links:
      - redis
