# frozen_string_literal: true

source 'https://rubygems.org'

# Simple, efficient background processing for Ruby.
gem 'sidekiq', '~> 6.5'
# Extends String class or add a ColorizedString with methods to set text color,
# background color and text effects.
gem 'colorize', '~> 0.8.1'
