# frozen_string_literal: true

source 'https://rubygems.org'

# Simple, efficient background processing for Ruby.
gem 'sidekiq', '~> 8.1'
# Extends String class or add a ColorizedString with methods to set text color,
# background color and text effects.
gem 'colorize', '~> 1.1'
# An XML toolkit for Ruby
gem 'rexml', '~> 3.4'
